### ISSUE TITLE
Compatibility with IntelliJ IDEA 2021.3

### ISSUE THREAD

**Issue by raphaelsaunier** [lukasbach/intellij-ts-react-livetemplates#1]
Hey Lukas, thanks for publishing this useful collection of snippets! 👍

It would be great to mark the plugin as compatible with the latest versions of IntelliJ (2021.3, as of this writing). 

For now, as a workaround I manually copied `TypedReact.xml` into my `templates/` configuration directory.

**Comment by lukasbach** [comment]
Hi, I just deployed a new version compatible with the latest IntelliJ versions that should be available on the marketplace once it has been approved by the marketplace team.

**Comment by lukasbach** [comment]
Should be available on marketplace, let me know if there are any other issues.

**Comment by raphaelsaunier** [comment]
Lovely! Working great in 2021.3 and 2022.1. 👌
