### ISSUE TITLE
Incompatible with new version of Webstorm

### ISSUE THREAD

**Issue by justin-hackin** [lukasbach/intellij-ts-react-livetemplates#10]
Webstorm version: WebStorm 2024.1 Build #WS-241.14494.235
OS: MacOS macOS 13.4 BuildVersion: 22F66

`Requires build 223.* or earlier` is displayed in the marketplace.

Thanks for making this, it has been useful to me 🙂

**Comment by lukasbach** [comment]
Hi, thanks for the report. Which plugin version are you on? 1.0.9 should support up to build 241, i.e. Webstorm 2024.1.1.

https://plugins.jetbrains.com/plugin/16796-live-templates-for-typescript-and-react/versions/stable/512964

**Comment by justin-hackin** [comment]
> Hi, thanks for the report. Which plugin version are you on? 1.0.9 should support up to build 241, i.e. Webstorm 2024.1.1.
> 
> https://plugins.jetbrains.com/plugin/16796-live-templates-for-typescript-and-react/versions/stable/512964

Whoops, you're right, I thought I updated it but maybe I needed a browser reset 🤷🏻‍♂️
