### ISSUE TITLE
Incompatible with latest WebStorm 2022.2 or 222.*

### ISSUE THREAD

**Issue by korri123** [lukasbach/intellij-ts-react-livetemplates#2]
Hey, thanks for this awesome plugin.

After updating WebStorm to 2022.2 it no longer seems to load unfortunately.

<img width="726" alt="image" src="https://user-images.githubusercontent.com/10642122/182705116-71f6d645-8c6f-4327-b91c-ba7e90183539.png">

**Comment by lukasbach** [comment]
I deployed another release with updated version numbers, once it is available in the marketplace (usually 2-3 days) it should be available in the latest version again.
