### ISSUE TITLE
Doesn't work in the newest version of Webstorm

### ISSUE THREAD

**Issue by allan-proventic** [lukasbach/intellij-ts-react-livetemplates#6]
**Describe the bug**
Doesn't work in the newest version of Webstorm build 231.

These live templates were very useful but is now incompatible with the newest update of Webstorm unfortunately.

**Comment by lukasbach** [comment]
I created an update earlier this week that was recently approved by Jetbrains which support up to IU-231.8770.17. Can you please try again?

**Comment by allan-proventic** [comment]
For some reason my Webstorm didn't show me there was an update for the plugin. So I tried to uninstall and reinstall the plugin, and now it works! Thanks!
